[project]
name = "toolbox-backend"
version = "0.1.0"
description = "API da plataforma de centralização de ferramentas utilizadas na Newnet"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "fastapi>=0.136.3",
    "pydantic[email]>=2.13.4",
    "pydantic-settings>=2.14.1",
    "sqlalchemy>=2.0.50",
    "uvicorn>=0.48.0",
    "asyncpg>=0.31.0",
    "psycopg>=3.3.4",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt==4.0.1",
    "python-jose[cryptography]>=3.5.0",
    "ruff>=0.15.16",
]
